const API = "https://api.github.com";
const OWNER = "HIT-Fireworks";
const CATEGORIES = new Set(["教材", "笔记", "课件", "试卷", "作业", "实验", "软件", "教程", "模板", "项目", "其他"]);
const TREE_CACHE = "public, max-age=31536000, s-maxage=31536000, immutable";
function json(value, status = 200, cache = "no-store") { return new Response(JSON.stringify(value), { status, headers: { "Content-Type": "application/json; charset=utf-8", "Cache-Control": cache } }); }
function safe(value) { try { const decoded = decodeURIComponent(value); return decoded && !decoded.includes("/") && decoded !== "." && decoded !== ".." ? decoded : ""; } catch { return ""; } }
function treeVersion(request) { const parts = new URL(request.url).pathname.split("/").filter(Boolean); const index = parts.indexOf("resource-tree"); return { repoId: safe(parts[index + 2]), commit: safe(parts[index + 3]), treeSha: safe((parts[index + 4] || "").replace(/\.json$/, "")) }; }
function authHeaders(env) { const headers = { Accept: "application/vnd.github+json", "User-Agent": "HIT-Fireworks-resource-tree", "X-GitHub-Api-Version": "2022-11-28" }; if (env?.GITHUB_TOKEN) headers.Authorization = `Bearer ${env.GITHUB_TOKEN}`; return headers; }
async function github(path, env) { const response = await fetch(`${API}${path}`, { headers: authHeaders(env) }); if (!response.ok) throw new Error(`GitHub API ${response.status}`); return response.json(); }
function normalize(repoId, commit, treeSha, tree) { const entries = tree.filter((item) => { const path = typeof item.path === "string" ? item.path : ""; return (item.type === "blob" || item.type === "tree") && CATEGORIES.has(path.split("/", 1)[0]) && !path.endsWith("/.gitkeep"); }).map((item) => ({ path: item.path, name: item.path.split("/").pop(), type: item.type, sha: item.sha, mode: item.mode, ...(typeof item.size === "number" ? { size: item.size } : {}), category: item.path.split("/", 1)[0] })).sort((a, b) => a.path.localeCompare(b.path, "zh-CN")); return { schemaVersion: 1, repoId, commit, treeSha, entries }; }
async function cacheGet(cache, key) { try { const response = await cache.match(key); return response ? response.json() : undefined; } catch { return undefined; } }
async function cachePut(cache, key, value) { try { await cache.put(key, new Response(JSON.stringify(value), { headers: { "Content-Type": "application/json", "Cache-Control": TREE_CACHE } })); } catch {} }
export async function onRequestGet(context) { const version = treeVersion(context.request); if (!version.repoId || !/^[a-f0-9]{40}$/.test(version.commit) || !/^[a-f0-9]{40}$/.test(version.treeSha)) return json({ error: "invalid_tree_version" }, 400); const cache = await caches.open("fireworks-resource-tree-v1"); const key = new Request(`https://fireworks.invalid/resource-tree/v1/${version.repoId}/${version.commit}/${version.treeSha}.json`); const hit = await cacheGet(cache, key); if (hit) return json(hit, 200, TREE_CACHE); try { const commit = await github(`/repos/${OWNER}/${encodeURIComponent(version.repoId)}/git/commits/${version.commit}`, context.env); if (commit.tree?.sha !== version.treeSha) return json({ error: "tree_commit_mismatch" }, 409); const tree = await github(`/repos/${OWNER}/${encodeURIComponent(version.repoId)}/git/trees/${version.treeSha}?recursive=1`, context.env); if (tree.truncated) return json({ error: "tree_truncated" }, 413); const value = normalize(version.repoId, version.commit, version.treeSha, tree.tree); await cachePut(cache, key, value); return json(value, 200, TREE_CACHE); } catch { return json({ error: "resource_tree_unavailable" }, 502); } }
export const __test = { treeVersion, normalize };
